### PR TITLE
Remote: Interact with a remote EcoTaxa server.

### PR DESCRIPTION
**Pull request by moi90**
- [x] Tests
- [x] Examples
- [x] Changelog

### CODE REVIEW

**Comment by moi90** [comment]
Please review and make suggestions :)

**Comment by jiho** [comment]
Looks good to me, although I am not really in a position to make any judgment. I made comments directly in the code.

One general question though: to extract data, you go through a full export every time, whereby you probably collect a lot of data you will not use. Have you explore the `objects` API (`object_set/{projid}/query` in particular)? Was something missing there?

**Comment by grololo06** [comment]
Hi,
If e.g. I remove the 'latin1' option in ExportReq, the code will break, and that's no big deal but could be surprising to ordinary users.
So, I would add a check on the Api version at startup (parsing https://ecotaxa.obs-vlfr.fr/api/openapi.json), in order to verify that the version is still indeed what you expect (i.e. 0.0.25 as I'm writing). If not, a big fat warning or even a full stop.

**Comment by moi90** [comment]
Thanks for looking into this!

> So, I would add a check on the Api version at startup (parsing https://ecotaxa.obs-vlfr.fr/api/openapi.json)

Does ecotaxa_py_client perform such a check and tells the user to upgrade if it is outdated?

Currently, many of the fields for ExportReq are required, although many of those only apply for certain `exp_type`s. I think it would be sensible to either a) provide sensible or null defaults for most of them (and validate later), or b) split the different export types into different API endpoints (e.g. `/object_set/export/bak`) (and have the respective required fields and sensible defaults transparent in openapi.json). (I would prefer b.)

Then, it wouldn't be a big issue if fields are added or removed when a user does not use them in the first place.

```
"required":["project_id","exp_type","tsv_entities","split_by","coma_as_separator","format_dates_times","with_images","with_internal_ids","only_first_image","sum_subtotal","out_to_ftp"]
```

Another question: Is BAK the only type where I can export images?

**Comment by moi90** [comment]
> One general question though: to extract data, you go through a full export every time, whereby you probably collect a lot of data you will not use. Have you explore the objects API (object_set/{projid}/query in particular)? Was something missing there?

I intended `pull` to get a complete snapshot of a project, possibly including images.
If you only need certain fields, [`/object_set/{project_id}/query`](https://ecotaxa.obs-vlfr.fr/api/docs#/objects/get_object_set) certainly is an option. (I have not tried it yet, but it seems cumbersome to use...)

And while I'm aware of [ecotaxa_py_client](https://github.com/ecotaxa/ecotaxa_py_client), I intended this interface here to be a bit more high-level.

If you don't have any objections, I will go on to merge it.

**Pull request merged**
