### PR TITLE
First implementation of read_tsv and write_tsv

### PR DESCRIPTION
**Pull request by moi90**
Basic preparations for packaging on PyPI.

## TODO
- [x] Decide content for `author` and `author_email` fields.

### CODE REVIEW

**Comment by moi90** [comment]
@jiho @rkiko @kimdonggyun Which values should be supplied for `author` and `author_email` fields? `author_email` could be preferably a mailing list that reaches the whole team.

**Comment by jiho** [comment]
I'd say: whoever commits the most code in the repo ;-)

**Comment by moi90** [comment]
Ok, for now this will be me :)

**Comment by moi90** [comment]
Please have a look if it works for you (in a testing virtual environment):

```sh
pip install git+https://github.com/moi90/pyecotaxa
```


```python
from pyecotaxa.archive import read_tsv
read_tsv("ecotaxa_export.tsv")
```

**Comment by moi90** [comment]
Also: What do you think about the `pyecotaxa.archive` namespace (as opposed to a future `pyecotaxa.api` one)?

**Comment by jiho** [comment]
> Please have a look if it works for you (in a testing virtual environment):
> 
> ```shell
> pip install git+https://github.com/moi90/pyecotaxa
> ```

Works fine

> ```python
> from pyecotaxa.archive import read_tsv
> read_tsv("ecotaxa_export.tsv")
> ```

But:

```
>>> read_tsv("~/gdrive/tmp/ecotaxa_export_859_20201105_2128.tsv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jiho/.local/lib/python3.6/site-packages/pyecotaxa/archive.py", line 58, in read_tsv
    return _fix_types(dataframe, enforce_types)
  File "/home/jiho/.local/lib/python3.6/site-packages/pyecotaxa/archive.py", line 26, in _fix_types
    raise ValueError("Unexpected type: {t!r}")
ValueError: Unexpected type: {t!r}
```

This is with an exported file, which does not have the second line with types. I would expect `read_tsv` to work with exported files too. Of course I could use `pandas.read_tsv` in that case but I think I won't be the only one to fall into that trap.

**Comment by jiho** [comment]
> Also: What do you think about the `pyecotaxa.archive` namespace (as opposed to a future `pyecotaxa.api` one)?

You know way more than I do regarding python programming conventions so, I'll leave it to you to decide!

**Comment by moi90** [comment]
> ValueError: Unexpected type: {t!r}

Another bug to fix: I forgot to make this an f-string.

> This is with an exported file, which does not have the second line with types.

Interesting! I thought all the tsv files exported by EcoTaxa contain this type annotation. Which do and which don't?

Can you pass me the first few lines of this file?

**Comment by jiho** [comment]
Just export any file and by default it won't have the second line. There used to be an option to add it and I don't even see it right now... 🤔

**Comment by moi90** [comment]
"Backup export" includes the line, "General export" doesn't ([taskexporttxt.py:253](https://github.com/oceanomics/ecotaxa_dev/blob/5664005c30337c90b7e585b468965ea574a84e4c/appli/tasks/taskexporttxt.py#L253)). What about the import implementation in EcoTaxa? Does it need this type header? Laurent said so:

> The TSV format we coded needs this second line, so I don't think it will work.

If the type header is in fact optional, I would, by default, not include it in the output.

**Comment by moi90** [comment]
@jiho It should now work with and without a type header.

**Comment by jiho** [comment]
> "Backup export" includes the line, "General export" doesn't ([taskexporttxt.py:253](https://github.com/oceanomics/ecotaxa_dev/blob/5664005c30337c90b7e585b468965ea574a84e4c/appli/tasks/taskexporttxt.py#L253)). What about the import implementation in EcoTaxa? Does it need this type header? 

It does.

**Comment by moi90** [comment]
So the type header should be included by default, unless the user chooses not to?

**Comment by moi90** [comment]
I was just bitten by this...

> Invalid Type '106814' for Field 'object_label' in file ecotaxa_kosmos_2017_update.tsv. Incorrect Type. Field ignored

**Comment by jiho** [comment]
> So the type header should be included by default, unless the user chooses not to?

It would be more consistent but less convenient; we chose convenience.
The real solution is to get rid of those type headers altogether and put them on the first line.

> I was just bitten by this...
> 
> > Invalid Type '106814' for Field 'object_label' in file ecotaxa_kosmos_2017_update.tsv. Incorrect Type. Field ignored

My way around this is to use `read_table(..., comment="[")`; that way, if the second line (which starts with `[`) is present it is skipped and if not, nothing changes. It would only fail if object ids (first column) start with `[`, which is fairly unlikely.

**Comment by moi90** [comment]
> My way around this is to use read_table(..., comment="[");

That's a clever hack, but not needed anymore with `pyecotaxa.read_tsv` ;)

**Pull request merged**
